blank_issues_enabled: false
contact_links:
  - name: Lieber ohne GitHub-Account?
    url: https://maximilianfiegen.de/nidus/#feedback
    about: Du kannst Feedback auch direkt über das Formular auf der Nidus-Seite schicken.
